const PLAYER = {

  NAME: 0,
  STATUS: 1,
  BASE_POINTS: 2,
  POINTS: 3,
  GAMES: 4,
  WINS: 5,
  LOSSES: 6,
  PEAK_POINTS: 7,
  ELO: 8,
  TIER: 9,
  UPDATED: 10,
  SEASON: 11,
  ACTIVE: 12,
  PLAYER_ID: 13,
  CAREER_WINS: 14,
  CAREER_LOSSES: 15,
  CAREER_GAMES: 16,
  CURRENT_RANK: 17,
  PREVIOUS_RANK: 18,
  CAREER_PEAK_ELO: 19

};

const SHEETS = {

  PLAYERS: 'PLAYERS',
  MATCH_HISTORY: 'MATCH_HISTORY',
  SETTINGS: 'SETTINGS',
  LEADERBOARD: 'LEADERBOARD',
  ACHIEVEMENTS: 'PLAYER_ACHIEVEMENTS',
  ACHIEVEMENT_METADATA: 'Achievement_Metadata',
  SEASON_RESULTS: 'SEASON_RESULTS',
  FORM_SUBMISSIONS: 'FORM_SUBMISSIONS',
  SEASONS_INDEX: 'SEASONS_INDEX'

};

const TKDL = {

  CACHE_SECONDS: 60,
  STARTING_ELO: 1000,
  STARTING_POINTS: 25,
  K_FACTOR: 32

};